# Docker Compose file for a Baikal server

version: "3"
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: app_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  
volumes:
  config:
  data:
  dbdata:
